### ISSUE TITLE
java.lang.IllegalArgumentException: column 'date_added' does not exist

### ISSUE THREAD

**Issue by myjij** [CodeBoy722/MediaFacer#19]
Dear CodeBoy722

thank you for great Media Library.

recenlty i using MediaFacer Library and i saw these error in logcat.

thanks.

 java.lang.IllegalArgumentException: column 'date_added' does not exist. Available columns: [_data, album_id, album, title, duration, artist, _display_name, _id, artist_id]  at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:351)
W/System.err:     at com.CodeBoy.MediaFacer.AudioGet.getAllAudioContent(AudioGet.java:72)

 java.lang.IllegalArgumentException: column 'date_modified' does not exist. Available columns: [_data, album_id, album, title, duration, artist, _display_name, _id, artist_id] W/System.err:     at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:351)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
        at com.CodeBoy.MediaFacer.AudioGet.getAllAudioContent(AudioGet.java:79)

**Comment by SaylesMand** [comment]
Hello!
Did you find the solution?
